services:
  db-mysql:
    container_name: marketplace_mysql
    image: 'mysql:8.0'
    restart: unless-stopped
    
    environment:
      - MYSQL_DATABASE=main_db
      - MYSQL_USER=GreatEgret
      - MYSQL_PASSWORD=ArdeaAlba
      - MYSQL_ROOT_PASSWORD=yes

    volumes:
      - ./db:/var/lib/mysql

    ports:
      - "3306:3306"
